# Pandas

In [1]:
import pandas as pd

In [31]:
data1= pd.read_csv("C:/Users/lenovo/Downloads/customer.csv", header=0)    

In [32]:
data1.head()
    

Customer ID    Customer Name    Segment  Age        Country  \
0    CG-12520      Claire Gute   Consumer   67  United States   
1    DV-13045  Darrin Van Huff  Corporate   31  United States   
2    SO-20335   Sean O'Donnell   Consumer   65  United States   
3    BH-11710  Brosina Hoffman   Consumer   20  United States   
4    AA-10480     Andrew Allen   Consumer   50  United States   

              City           State  Postal Code Region  
0        Henderson        Kentucky        42420  South  
1      Los Angeles      California        90036   West  
2  Fort Lauderdale         Florida        33311  South  
3      Los Angeles      California        90032   West  
4          Concord  North Carolina        28027  South

In [33]:
data1.head(10)

Customer ID       Customer Name      Segment  Age        Country  \
0    CG-12520         Claire Gute     Consumer   67  United States   
1    DV-13045     Darrin Van Huff    Corporate   31  United States   
2    SO-20335      Sean O'Donnell     Consumer   65  United States   
3    BH-11710     Brosina Hoffman     Consumer   20  United States   
4    AA-10480        Andrew Allen     Consumer   50  United States   
5    IM-15070        Irene Maddox     Consumer   66  United States   
6    HP-14815       Harold Pawlan  Home Office   20  United States   
7    PK-19075           Pete Kriz     Consumer   46  United States   
8    AG-10270     Alejandro Grove     Consumer   18  United States   
9    ZD-21925  Zuschuss Donatelli     Consumer   66  United States   

              City           State  Postal Code   Region  
0        Henderson        Kentucky        42420    South  
1      Los Angeles      California        90036     West  
2  Fort Lauderdale         Florida        33311    South  
3      Los Angeles      California        90032     West  
4          Concord  North Carolina        28027    South  
5          Seattle      Washington        98103     West  
6       Fort Worth           Texas        76106  Central  
7          Madison       Wisconsin        53711  Central  
8      West Jordan            Utah        84084     West  
9    San Francisco      California        94109     West

In [34]:
data2= pd.read_csv("C:/Users/lenovo/Downloads/customer.csv", header=0, index_col=0)    

In [35]:
data2.head()

Customer Name    Segment  Age        Country             City  \
Customer ID                                                                    
CG-12520         Claire Gute   Consumer   67  United States        Henderson   
DV-13045     Darrin Van Huff  Corporate   31  United States      Los Angeles   
SO-20335      Sean O'Donnell   Consumer   65  United States  Fort Lauderdale   
BH-11710     Brosina Hoffman   Consumer   20  United States      Los Angeles   
AA-10480        Andrew Allen   Consumer   50  United States          Concord   

                      State  Postal Code Region  
Customer ID                                      
CG-12520           Kentucky        42420  South  
DV-13045         California        90036   West  
SO-20335            Florida        33311  South  
BH-11710         California        90032   West  
AA-10480     North Carolina        28027  South

In [36]:
data2.head(10)

Customer Name      Segment  Age        Country  \
Customer ID                                                        
CG-12520            Claire Gute     Consumer   67  United States   
DV-13045        Darrin Van Huff    Corporate   31  United States   
SO-20335         Sean O'Donnell     Consumer   65  United States   
BH-11710        Brosina Hoffman     Consumer   20  United States   
AA-10480           Andrew Allen     Consumer   50  United States   
IM-15070           Irene Maddox     Consumer   66  United States   
HP-14815          Harold Pawlan  Home Office   20  United States   
PK-19075              Pete Kriz     Consumer   46  United States   
AG-10270        Alejandro Grove     Consumer   18  United States   
ZD-21925     Zuschuss Donatelli     Consumer   66  United States   

                        City           State  Postal Code   Region  
Customer ID                                                         
CG-12520           Henderson        Kentucky        42420    South  
DV-13045         Los Angeles      California        90036     West  
SO-20335     Fort Lauderdale         Florida        33311    South  
BH-11710         Los Angeles      California        90032     West  
AA-10480             Concord  North Carolina        28027    South  
IM-15070             Seattle      Washington        98103     West  
HP-14815          Fort Worth           Texas        76106  Central  
PK-19075             Madison       Wisconsin        53711  Central  
AG-10270         West Jordan            Utah        84084     West  
ZD-21925       San Francisco      California        94109     West

In [37]:
  data1.describe()

Age   Postal Code
count  793.000000    793.000000
mean    44.467844  55229.717528
std     15.526673  31679.223816
min     18.000000   1841.000000
25%     31.000000  27217.000000
50%     45.000000  55901.000000
75%     58.000000  90004.000000
max     70.000000  99207.000000

In [38]:
data1.iloc[0]

Customer ID           CG-12520
Customer Name      Claire Gute
Segment               Consumer
Age                         67
Country          United States
City                 Henderson
State                 Kentucky
Postal Code              42420
Region                   South
Name: 0, dtype: object

In [39]:
import numpy as np
import pandas as pd

series in pandas is data containing single row or single column

In [40]:
d1= np.arange(1,10)

In [41]:
d1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
 lst =[1,2,3,4,5,]

In [43]:
lst

[1, 2, 3, 4, 5]

In [44]:
lst1=[5,6,7]
lst1


[5, 6, 7]

In [45]:
arr=np.array(lst1)

In [46]:
arr

array([5, 6, 7])

In [47]:
myseries= pd.Series(lst1)
print(myseries)

0    5
1    6
2    7
dtype: int64


In [48]:
print(myseries[2])

7


In [49]:
label=["zero","first","second"]

In [50]:
label

['zero', 'first', 'second']

In [22]:
series1= pd.Series(data=arr,index=label)

In [23]:
series1

zero      5
first     6
second    7
dtype: int32

In [26]:
df= pd.DataFrame(np.random.randn(4,4))

In [27]:
df

0         1         2         3
0  0.278338 -0.464609 -1.432176 -0.598935
1  0.763005 -0.476459  0.794243  1.109913
2  0.586244  0.688514  0.526423  0.031946
3 -0.081299  1.440084  0.482988 -1.132665

In [30]:
lst=[1,2,3,3,4]
np.array(lst)

array([1, 2, 3, 3, 4])

In [31]:
lst1=[2,5,6,7,8]
np.array(lst1)

array([2, 5, 6, 7, 8])

In [37]:
b=pd.Series(lst)
b

0    1
1    2
2    3
3    3
4    4
dtype: int64

In [38]:
a=pd.Series(lst1)
a

0    2
1    5
2    6
3    7
4    8
dtype: int64

In [40]:
df

0         1         2         3
0  0.278338 -0.464609 -1.432176 -0.598935
1  0.763005 -0.476459  0.794243  1.109913
2  0.586244  0.688514  0.526423  0.031946
3 -0.081299  1.440084  0.482988 -1.132665

In [47]:
df1= pd.concat([a,b],axis=1,sort=False)

In [48]:
df1

0  1
0  2  1
1  5  2
2  6  3
3  7  3
4  8  4

In [49]:
df2= pd.DataFrame(np.random.randn(6,6))

In [50]:
df2

0         1         2         3         4         5
0 -1.109397  1.344920  0.088326 -0.738498 -2.069786 -0.855030
1  0.296085 -1.564315  0.249277  1.833808  1.247462  0.342212
2 -0.086797  0.029721 -0.614671 -1.642633  1.938365  1.267625
3  1.800597 -0.942294  0.395070  0.669090 -0.131806 -0.126575
4  1.729736  0.832291 -2.203150  0.759029 -1.392422 -0.722241
5 -0.332684  0.951412 -2.620954 -0.776187 -0.800968 -0.019547

In [58]:
print(df2[2])

0    0.088326
1    0.249277
2   -0.614671
3    0.395070
4   -2.203150
5   -2.620954
Name: 2, dtype: float64


accessing and modifying

In [63]:
df2[[1,2]]

1         2
0  1.344920  0.088326
1 -1.564315  0.249277
2  0.029721 -0.614671
3 -0.942294  0.395070
4  0.832291 -2.203150
5  0.951412 -2.620954

In [66]:
df2.iloc[0]

0   -1.109397
1    1.344920
2    0.088326
3   -0.738498
4   -2.069786
5   -0.855030
Name: 0, dtype: float64

In [65]:
df2.loc[1,2]

0.24927677165566567

In [5]:
df3= pd.DataFrame({"id":[1,2,3,4,5,6],
                   "name":["Ankit","Arun","Gautam","Rakesh","Shivam","Suryansh"],
                   "salary in lacs":[3.000,3.000,3.000,3.000,3.000,3.000]})
df3

id      name  salary in lacs
0   1     Ankit             3.0
1   2      Arun             3.0
2   3    Gautam             3.0
3   4    Rakesh             3.0
4   5    Shivam             3.0
5   6  Suryansh             3.0

In [4]:
df4= pd.DataFrame({"id":[1,2,3,4,5,6],
                   "name":["alex","ari","hazel","harshit","sofia","sonam"],
                   "roll no":[1,2,3,4,5,6]})
df4

id     name  roll no
0   1     alex        1
1   2      ari        2
2   3    hazel        3
3   4  harshit        4
4   5    sofia        5
5   6    sonam        6

In [6]:
pd.concat([df3,df4],axis=1,sort=True)

id      name  salary in lacs  id     name  roll no
0   1     Ankit             3.0   1     alex        1
1   2      Arun             3.0   2      ari        2
2   3    Gautam             3.0   3    hazel        3
3   4    Rakesh             3.0   4  harshit        4
4   5    Shivam             3.0   5    sofia        5
5   6  Suryansh             3.0   6    sonam        6

In [7]:
pd.merge(df3,df4, on ="id", how="left")

id    name_x  salary in lacs   name_y  roll no
0   1     Ankit             3.0     alex        1
1   2      Arun             3.0      ari        2
2   3    Gautam             3.0    hazel        3
3   4    Rakesh             3.0  harshit        4
4   5    Shivam             3.0    sofia        5
5   6  Suryansh             3.0    sonam        6

In [8]:
pd.merge(df3,df4, on ="id", how="left",indicator=True)

id    name_x  salary in lacs   name_y  roll no _merge
0   1     Ankit             3.0     alex        1   both
1   2      Arun             3.0      ari        2   both
2   3    Gautam             3.0    hazel        3   both
3   4    Rakesh             3.0  harshit        4   both
4   5    Shivam             3.0    sofia        5   both
5   6  Suryansh             3.0    sonam        6   both

In [10]:
df3["salary in lacs"].unique()

array([3.])

In [13]:
df3["id"].value_counts()

6    1
5    1
4    1
3    1
2    1
1    1
Name: id, dtype: int64

In [15]:
df3.columns

Index(['id', 'name', 'salary in lacs'], dtype='object')

In [16]:
def salary(s):
    return s*2.0


In [17]:
df3["salary in lacs"].apply(salary)

0    6.0
1    6.0
2    6.0
3    6.0
4    6.0
5    6.0
Name: salary in lacs, dtype: float64

In [19]:
df3.mean()

id                3.5
salary in lacs    3.0
dtype: float64

In [20]:
df3.std()

id                1.870829
salary in lacs    0.000000
dtype: float64

In [22]:
df3.var()

id                3.5
salary in lacs    0.0
dtype: float64

In [24]:
df3["id"].max()

6

In [25]:
df3["name"].apply(len)
    

0    5
1    4
2    6
3    6
4    6
5    8
Name: name, dtype: int64

In [27]:
df3.sort_values(by="name")

id      name  salary in lacs
0   1     Ankit             3.0
1   2      Arun             3.0
2   3    Gautam             3.0
3   4    Rakesh             3.0
4   5    Shivam             3.0
5   6  Suryansh             3.0

In [32]:
df3

name  salary in lacs
0     Ankit             3.0
1      Arun             3.0
2    Gautam             3.0
3    Rakesh             3.0
4    Shivam             3.0
5  Suryansh             3.0

In [30]:
df3

name  salary in lacs
0     Ankit             3.0
1      Arun             3.0
2    Gautam             3.0
3    Rakesh             3.0
4    Shivam             3.0
5  Suryansh             3.0

In [37]:
mydict={"customer":["cust1","cust2","cust3","cust4","cust5"],
                    "product1":[1.1,2.1,9.0,7.9,8.8],
                    "product2":[1.4,9,5,8,7]}
df6=pd.DataFrame(mydict,index=["purchase1","purchase2","purchase3","purchase4","purchase5"])                    

In [38]:
df6

customer  product1  product2
purchase1    cust1       1.1       1.4
purchase2    cust2       2.1       9.0
purchase3    cust3       9.0       5.0
purchase4    cust4       7.9       8.0
purchase5    cust5       8.8       7.0

In [39]:
g= df6.groupby("customer")

In [46]:
g

In [45]:
g.describe()

product1                                   product2                \
            count mean std  min  25%  50%  75%  max    count mean std  min   
customer                                                                     
cust1         1.0  1.1 NaN  1.1  1.1  1.1  1.1  1.1      1.0  1.4 NaN  1.4   
cust2         1.0  2.1 NaN  2.1  2.1  2.1  2.1  2.1      1.0  9.0 NaN  9.0   
cust3         1.0  9.0 NaN  9.0  9.0  9.0  9.0  9.0      1.0  5.0 NaN  5.0   
cust4         1.0  7.9 NaN  7.9  7.9  7.9  7.9  7.9      1.0  8.0 NaN  8.0   
cust5         1.0  8.8 NaN  8.8  8.8  8.8  8.8  8.8      1.0  7.0 NaN  7.0   

                              
          25%  50%  75%  max  
customer                      
cust1     1.4  1.4  1.4  1.4  
cust2     9.0  9.0  9.0  9.0  
cust3     5.0  5.0  5.0  5.0  
cust4     8.0  8.0  8.0  8.0  
cust5     7.0  7.0  7.0  7.0

In [44]:
for customer, customer_df in g:
    print(customer)
    print(customer_df)

cust1
          customer  product1  product2
purchase1    cust1       1.1       1.4
cust2
          customer  product1  product2
purchase2    cust2       2.1       9.0
cust3
          customer  product1  product2
purchase3    cust3       9.0       5.0
cust4
          customer  product1  product2
purchase4    cust4       7.9       8.0
cust5
          customer  product1  product2
purchase5    cust5       8.8       7.0


In [48]:
g.get_group("cust1")

customer  product1  product2
purchase1    cust1       1.1       1.4

In [49]:
g.max()

product1  product2
customer                    
cust1          1.1       1.4
cust2          2.1       9.0
cust3          9.0       5.0
cust4          7.9       8.0
cust5          8.8       7.0

In [53]:
import pandas as pd
di= pd.read_csv("C:/Users/lenovo/Downloads/diabetes.csv")

In [57]:
di

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]